export const projectData = [
  {
    title: "FullStack Blog App",
    skills: "MERN Stack, Tailwind, Cloudinary",
    description: "",
    img: "/projects/blog-tech.png",
    link: "https://blog-tech-delta.vercel.app/",
    repo: "https://github.com/LakshayBabbar/Blog-App",
    id: 0,
  },
  {
    title: "Code Editor",
    skills: "Next.js 14, Firebase",
    description: "",
    img: "/projects/codeframer.webp",
    link: "https://code-framer.vercel.app/",
    repo: "https://github.com/LakshayBabbar/CodeFramer",
    id: 1,
  },
  {
    title: "Amazon UI Clone",
    skills: "React.js",
    description: "",
    img: "/projects/amazon.webp",
    link: "https://lakshaybabbar.github.io/Amazon-Clone/",
    repo: "https://github.com/LakshayBabbar/Amazon-Clone",
    id: 2,
  },
  {
    title: "Studio Landing Page",
    skills: "HTML, CSS, JS, SMTPJS",
    description: "",
    img: "/projects/studio.webp",
    link: "https://lakshaybabbar.github.io/Lakshay-Movies-Studio/",
    repo: "https://github.com/LakshayBabbar/Lakshay-Movies-Studio",
    id: 3,
  },
  {
    title: "Todo-List App",
    skills: "React.js",
    description: "",
    img: "/projects/todo.webp",
    link: "https://todo-list-vanilla-react.vercel.app/",
    repo: "https://github.com/LakshayBabbar/Todo-App",
    id: 4,
  },
];